---
# Call 61502-automation playbooks

- include_role:
    name: "{{ repos_path }}/61502-automation/automation/roles/install_logging_from_subscription"
  vars:
    cluster_address: "{{ ocp_cluster_address }}"
...